#pragma once

#include "NativeGameplayTags.h"

namespace CatFishingGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CastLanded);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CastFailed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProbeTriggered);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProbeCompleted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FishSelectionFailed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EarlyHook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HookAccepted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WindowExpired);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FishStaminaDepleted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CatStaminaDepleted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CatOverpowered);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RodBroken);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AutoHaulReachedShore);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AutoHaulFailed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScoopCommitted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interrupted);
}
