#pragma once

#include "NativeGameplayTags.h"

namespace CatFishingGameplayTags
{
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CastLanded);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CastFailed);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProbeTriggered);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProbeCompleted);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FishSelectionFailed);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EarlyHook);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HookAccepted);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WindowExpired);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RodBroken);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LineBroken);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AutoHaulReachedShore);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AutoHaulFailed);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScoopCommitted);
	CATFISHING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interrupted);
}
