#include "AbilitySystem/Tags/CatFishingAbilityTags.h"

namespace CatFishingAbilityTags
{
	UE_DEFINE_GAMEPLAY_TAG(Input_Fishing_RodInteract, "Cat.Input.Fishing.RodInteract");
	UE_DEFINE_GAMEPLAY_TAG(Input_Fishing_Primary, "Cat.Input.Fishing.Primary");
	UE_DEFINE_GAMEPLAY_TAG(Input_Fishing_Cancel, "Cat.Input.Fishing.Cancel");
	UE_DEFINE_GAMEPLAY_TAG(Input_Fishing_Scoop, "Cat.Input.Fishing.Scoop");
	UE_DEFINE_GAMEPLAY_TAG(Input_Fishing_Chum, "Cat.Input.Fishing.Chum");
	UE_DEFINE_GAMEPLAY_TAG(Input_Fishing_Slack, "Cat.Input.Fishing.Slack");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Fishing_RodInteract, "Cat.Ability.Fishing.RodInteract");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Fishing_Primary, "Cat.Ability.Fishing.Primary");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Fishing_Cancel, "Cat.Ability.Fishing.Cancel");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Fishing_Scoop, "Cat.Ability.Fishing.Scoop");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Fishing_Chum, "Cat.Ability.Fishing.Chum");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Fishing_Slack, "Cat.Ability.Fishing.Slack");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Body_Action, "Cat.Ability.Body.Action");
	UE_DEFINE_GAMEPLAY_TAG(Ability_ActivationPolicy_OnInputTriggered, "Cat.Ability.ActivationPolicy.OnInputTriggered");
	UE_DEFINE_GAMEPLAY_TAG(Ability_ActivationPolicy_WhileInputActive, "Cat.Ability.ActivationPolicy.WhileInputActive");
	UE_DEFINE_GAMEPLAY_TAG(Ability_ActivationPolicy_OnGranted, "Cat.Ability.ActivationPolicy.OnGranted");
	UE_DEFINE_GAMEPLAY_TAG(State_Fishing_Aiming, "Cat.State.Fishing.Aiming");
	UE_DEFINE_GAMEPLAY_TAG(State_Fishing_Reeling, "Cat.State.Fishing.Reeling");
	UE_DEFINE_GAMEPLAY_TAG(State_Fishing_Scooping, "Cat.State.Fishing.Scooping");
	UE_DEFINE_GAMEPLAY_TAG(State_Fishing_RodOperating, "Cat.State.Fishing.RodOperating");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Fishing_Scoop, "Cat.Cooldown.Fishing.Scoop");
	UE_DEFINE_GAMEPLAY_TAG(AbilityEvent_Body_CampRest, "Cat.Ability.Event.Body.CampRest");
	UE_DEFINE_GAMEPLAY_TAG(AbilityEvent_Body_CampfirePlayback, "Cat.Ability.Event.Body.CampfirePlayback");
	UE_DEFINE_GAMEPLAY_TAG(AbilityEvent_Body_RescueCharacterToCamp, "Cat.Ability.Event.Body.RescueCharacterToCamp");
	UE_DEFINE_GAMEPLAY_TAG(AbilityEvent_Body_RequestManualHelp, "Cat.Ability.Event.Body.RequestManualHelp");
	UE_DEFINE_GAMEPLAY_TAG(AbilityEvent_Body_RequestMischief, "Cat.Ability.Event.Body.RequestMischief");
	UE_DEFINE_GAMEPLAY_TAG(AbilityEvent_Body_PlaceProtectionSign, "Cat.Ability.Event.Body.PlaceProtectionSign");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Fishing_Cast, "Cat.GameplayCue.Fishing.Cast");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Fishing_Reel, "Cat.GameplayCue.Fishing.Reel");
	UE_DEFINE_GAMEPLAY_TAG(Cosmetic_Fishing_ScoopSwing, "Cat.Cosmetic.Fishing.ScoopSwing");
	UE_DEFINE_GAMEPLAY_TAG(Cosmetic_Fishing_HookPull, "Cat.Cosmetic.Fishing.HookPull");
	UE_DEFINE_GAMEPLAY_TAG(Cosmetic_Fishing_LineCut, "Cat.Cosmetic.Fishing.LineCut");
	UE_DEFINE_GAMEPLAY_TAG(Cosmetic_Fishing_CatInWater, "Cat.Cosmetic.Fishing.CatInWater");
	UE_DEFINE_GAMEPLAY_TAG(Data_Fishing_FightStaminaDelta, "Cat.Data.Fishing.FightStaminaDelta");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_BaseDailyOfferingTarget, "Cat.Data.Run.BaseDailyOfferingTarget");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_SmallFishCount, "Cat.Data.Run.Offering.SmallFishCount");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_MediumFishCount, "Cat.Data.Run.Offering.MediumFishCount");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_LargeFishCount, "Cat.Data.Run.Offering.LargeFishCount");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_GiantFishCount, "Cat.Data.Run.Offering.GiantFishCount");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_StinkyFishCount, "Cat.Data.Run.Offering.StinkyFishCount");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_BaseProgressGain, "Cat.Data.Run.Offering.BaseProgressGain");
	UE_DEFINE_GAMEPLAY_TAG(Data_Run_Offering_BaseProgressLoss, "Cat.Data.Run.Offering.BaseProgressLoss");
}
